[features]
seeds = false
[programs.devnet]
myepicproject = "CFCdgxTd9GsY9BfRvwfYxZzMQfFWcBvAYYZhDdjfmxGp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/lodgendury/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 

